### ISSUE TITLE
Add LICENSE

### ISSUE THREAD

**Issue by benny-n** [benny-n/gear#2]

**Comment by IliaFeldgun** [comment]
Need to decide if we want to force anybody using us to disclose **their** source.
The other option is not forcing.

**Comment by benny-n** [comment]
@M-Wittner @orenkoren @grishatsuker @NaorHaba @liadaram1 @eitangreenb @IliaFeldgun 

Please vote:

[![](https://api.gh-polls.com/poll/01FB30NMW3BKTMFRGYET2K72GB/Force%20anybody%20using%20us%20to%20disclose%20their%20source.)](https://api.gh-polls.com/poll/01FB30NMW3BKTMFRGYET2K72GB/Force%20anybody%20using%20us%20to%20disclose%20their%20source./vote)
[![](https://api.gh-polls.com/poll/01FB30NMW3BKTMFRGYET2K72GB/Do%20not%20force%20anybody%20using%20us%20to%20disclose%20their%20source.)](https://api.gh-polls.com/poll/01FB30NMW3BKTMFRGYET2K72GB/Do%20not%20force%20anybody%20using%20us%20to%20disclose%20their%20source./vote)

**Comment by IliaFeldgun** [comment]
https://choosealicense.com/licenses/bsd-3-clause/

**Comment by IliaFeldgun** [comment]
https://doc.rust-lang.org/cargo/reference/manifest.html#the-license-and-license-file-fields
