### ISSUE TITLE
CI pipeline and development branch

### ISSUE THREAD

**Issue by benny-n** [benny-n/gear#5]
Do we maintain a development branch and everyone pushes changes to it or do we open a branch per issue? Maybe something in the middle? 
Also, should we add some sort of CI pipeline?
Please share your ideas regarding these questions

**Comment by grishatsuker** [comment]
In my opinion, the bare minimum for development should involve this, in a generic manner.
- Compile code (fail pipe if error occurs, maybe warning tolerant maybe not)
- Run unit tests on module, (fail pipe if fails)
- Build docker image (for each distro, at least windows and linux)
- Upload to docker hub (ofcourse)
- Use an image registry for versioning.

I feel that all of this can easily fit the git-actions mechanisms, and we wont need to actually use jenkins for our needs for now.

**Comment by benny-n** [comment]
Sounds good, I'm assigning you to this @grishatsuker .
What about branch methodology? 
Single developement branch or branch for each issue/task?

**Comment by grishatsuker** [comment]
@benny-n
I support branching for features and using **git-flow methodology** (Or at least the paradigm), It allows smooth collaboration while not polluting our development branch (Which should be treated nearly as master branch).

Here's a small read:
https://danielkummer.github.io/git-flow-cheatsheet/

An example for a legit flow:
- Issue is opened, something needs to be developped
- Developer opens a branch, names it by the name of the issue.
- Developer pulls develop, to ensure he's up to date. with the latest release.
- Development happens inside the branch.
- Pull develop again, to ensure that if anything was merged into develop while working on this branch are reflected inside.
- MR into develop

**Comment by benny-n** [comment]
#16
